---
- name: Configure extra package repositories
  ansible.builtin.dnf:
    name: epel-release
    state: present
  when: ansible_distribution in ['Rocky', 'AlmaLinux', 'CentOS', 'RedHat']

- name: Install core utilities via DNF
  ansible.builtin.dnf:
    name:
      - zsh
      - fzf
      - ripgrep
      - fd-find
      - bat
      - git
      - curl
      - unzip
    state: present

- name: Install Starship
  ansible.builtin.include_tasks: install_gh_release.yml
  vars:
    gh_app_name: "Starship"
    gh_repo: "starship/starship"
    gh_asset_name: "starship-x86_64-unknown-linux-musl.tar.gz"
    gh_binary_path: "/usr/local/bin/starship"
    gh_selinux: true

- name: Install eza
  ansible.builtin.include_tasks: install_gh_release.yml
  vars:
    gh_app_name: "Eza"
    gh_repo: "eza-community/eza"
    gh_asset_name: "eza_x86_64-unknown-linux-musl.tar.gz"
    gh_binary_path: "/usr/local/bin/eza"
    gh_selinux: true
