---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    target_username: "testuser"
  tasks:
    - name: Scaffold target user account
      ansible.builtin.user:
        name: "{{ target_username }}"
        state: present

    - name: Include container_host
      ansible.builtin.include_role:
        name: container_host
