---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance-fedora
    image: docker.io/geerlingguy/docker-fedora39-ansible:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  - name: instance-rocky
    image: docker.io/geerlingguy/docker-rockylinux9-ansible:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: '../../../:$ANSIBLE_ROLES_PATH'
  config_options:
    defaults:
      callback_whitelist: profile_tasks
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
